eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8090
spring:
  application:
    name: servico-zuul-server
zuul:
  routes:
    items:
      path: /api/it/**
      service-id: servico-items
    produtos:
      path: /api/prod/**
      service-id: servico-produtos
    usuarios:
      path: /api/usuarios/**
      service-id: servico-usuarios
    security:
      path: /api/security/**
      service-id: servico-oauth
      sensitive-headers:
        - Cookie
        - Set-Cookie 
